version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - 3000:3000
    restart: always
    tty: true
    volumes:
      - ./frontend/app:/usr/src/app/next
      - node_modules_volume:/frontend/app/node_modules
  
  backend:
    container_name: backend
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - 8000:8000
    restart: always
    tty: true
    volumes:
      - ./backend/app:/app
      - site-packages:/usr/local/lib/python3.7/site-packages
      
  db:
    image: mysql
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker_db
      MYSQL_USER: docker_user
      MYSQL_PASSWORD: docker_pass
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=docker_user
      - PMA_PASSWORD=docker_pass
    ports:
      - "8080:80"
    volumes:
      - ./phpmyadmin/sessions:/sessions

volumes:
  node_modules_volume:
  site-packages: